"""empty message

Revision ID: 55c5d29f1fe2
Revises: 6919ab9a3841
Create Date: 2024-05-05 16:16:56.957534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55c5d29f1fe2'
down_revision: Union[str, None] = '6919ab9a3841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('name', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'files', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files', type_='unique')
    op.drop_column('files', 'name')
    # ### end Alembic commands ###
